#!/bin/bash
#
# This script backup files in ~/bak/backup to /backup
#

configfile="$HOME/.mbackup/config"

if ! [ -e $configfile ]; then
	echo "mb: error: mbackup config file $configfile not found."
	exit 1
fi

. $configfile

OPTIONS=" -h --itemize-changes --delete-during -a -r --log-file=/var/log/mbackup.log --files-from=$backuplist --exclude-from=$excludelist "

#backup files to $targetdir
sudo rsync $OPTIONS / $targetdir

#[optional]move backup files to external media
#Usage:
#  mb /path/to/media [init]
#Sample:
#  mb /media/BAKUP/
#  mb /media/BAKUP/ init

# this script helps you trim last slash(/) in string
# please use $trimedstr to get the trimed
function trim_last_slash
{
    orgstr=$1
    slash="/"
    empty=""
    trimedstr=${orgstr/%$slash/$empty}
}

if [ $? -ne 0 ]
then
	echo "`date +"%F %r"`       rsync: some error occurred!"
	exit 1
else
	if [ -n "$1" ]
	then
		TAR="$1"
		# remove trailing / in $TAR if it is there
                trim_last_slash $TAR
                TAR=$trimedstr

		if [ -d $TAR ]
		then
			echo "now backup files to extra directory[$TAR]"
                        # please note backup to external dir use /backup as src
                        # not the ~/backup file list, so don't change the cmd
                        # unless you know what you are doing
			if [ "$2" == "init" ]
			then
				if [ -d $TAR/backup ]
				then
					echo "old backup detected. please rename $TAR/backup before trying init backup."
					echo "or all old files may get deleted!"
					exit 0
				fi
				sudo rsync -h --delete-during -a -r --log-file=/var/log/mbackup.log $targetdir $TAR
			else
				# show what's updated
				sudo rsync -h --itemize-changes --delete-during -a -r --log-file=/var/log/mbackup.log $targetdir $TAR
			fi
			exit $?
		else
			echo "directory [$TAR] does not exists! backup has quit!"
			exit 0
		fi
	fi
fi

#check backup list, give a warning if backup list file is more than 3-day-old
/home/sylecn/bin/cbl $backuplist

