#!/bin/sh 
#cron backup script for root

filelist="/home/sylecn/bak/backup"
excludelist="/home/sylecn/bak/backup.exclude"

/usr/bin/rsync -q -h --delete-during -a -r --log-file=/var/log/mbackup.log --files-from=$filelist --exclude-from=$excludelist / /backup

#check backup list, give a warning if backup list file is more than 3-day-old
/home/sylecn/bin/cbl

if [ $? -ne 0 ]
then
    #send err via mail
    echo "`date +"%F %r"`        cron mbackup(rsync) error occurred"
    #log err on file
    echo "`date +"%F %r"`        cron mbackup(rsync) error occurred" >> /var/log/mbackup.err
fi

