#!/bin/bash 
#
# file:
#   ~/bin/ubl
#   ~/.mbackup/ubl.d/
# description:
#   update backup list for mbackup projects

#
# read config file
#

configfile="$HOME/.mbackup/config"

if ! [ -e $configfile ]; then
	echo "ubl: error: mbackup config file $configfile not found."
	exit $EE_CONFIG_NOT_FOUND
fi

. $configfile

#
# functions
#

## debug output
debug () {
	[ $DEBUG -eq 1 ] && echo "$*"
}

print_a_dot () {
	echo -n "."
}

## Usage: remove_duplicated_lines filename
## remove duplicated lines in given file
remove_duplicated_lines () {
	if [ -z "$1" ]; then
		echo "remove_duplicated_lines: error: no filename given."
		return 1
	fi
	if ! [ -e "$1" ]; then
		echo "remove_duplicated_lines: error: file not exists: $1."
		return 1
	fi
	filename="$1"
	tmpfile="$filename".tmp
	cp $filename $tmpfile
	/usr/bin/sort "$tmpfile" | /usr/bin/uniq > "$filename"
	rm $tmpfile
}

## set to 1 to enable debug output
DEBUG=0
EE_CONFIG_NOT_FOUND=1

#
# source files in ubl.d dir
#

cd $ubl_dir
if [ -z "$1" ]; then
        for ubl_script in `ls [0-9]*`; do
                . ${ubl_dir}/$ubl_script
        done
else
        #sh
        case "$1" in
                "."|"main"|"ubl")
                echo "ubl-mb"
                . ${ubl_dir}/10pre-ubl
                . ${ubl_dir}/20ubl
                ;;
                "rsync")
                echo "ubl-rsync"
                . ${ubl_dir}/20rsync
                ;;
        esac
fi

echo "done."

exit 0
