#!/bin/bash 
#
# file:
#   ~/bin/update-backup-list
# description:
#   generate ~/bak/backup
#   that file is used as a file list which needs backup by mb or mbackup

#TODO auto remove non-exist files and give warning when merging svimlog

echo "updating backup list..."

#update ~/bak/backup.svimfiles
/usr/bin/sort $HOME/bak/svimlog | /usr/bin/uniq > $HOME/bak/backup.svimfiles

#update ~/bak/backup
cd $HOME/bak
cat backup.header backup.userlist backup.svimfiles > backup

echo "done."

exit 0
