#!/bin/bash
#
# This script backup files from $backuplist to rsync.net server.
# use mbackup lists:
#     backuplist="${backuplistsdir}/auto.backup"
#     excludelist="${backuplistsdir}/auto.exclude"
# and in addition:
#     exclude one more file:
#     rsync_exclude="${backuplistsdir}/user.private"

configfile="$HOME/.mbackup/config"

if ! [ -e $configfile ]; then
	echo "mb: error: mbackup config file $configfile not found."
	exit 1
fi

. $configfile

echo "backup files to rsync.net server"

# use sylecn's ssh config and private key
# don't show progress for each file when using "mb-online init"
# use two exclude file
INITOPTIONS="-e 'ssh -F /home/sylecn/.ssh/config -i /home/sylecn/.ssh/id_rsa' -h --delete-during -a -r --log-file=$rsync_net_log --files-from=$backuplist --exclude-from=$rsync_exclude --exclude-from=$excludelist"
OPTIONS="--itemize-changes $INITOPTIONS"

TAR=rsync:backup/

if [ "$1" == "init" ]
then
	# when doing init tranfer
	# show error if the target dir exists.
	ssh rsync ls backup/ > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		echo "mb-online: error: old backup detected. "
		echo "please rename rsync:backup/, or old files may get deleted!"
		exit 1
	fi
	# without eval rsync gives parse syntax error
	eval sudo rsync $INITOPTIONS / $TAR
else
        # show what's being updated
	eval sudo rsync $OPTIONS / $TAR
fi

#TODO now how to backup things in user.private
#     local gpg then upload? use duplicity?
