#!/bin/bash
#
# This script backup files from /backup/ to rsync.net server.
# exclude files on private list: user.private
#

PATH=/home/sylecn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

configfile="$HOME/.mbackup/config"

if ! [ -e $configfile ]; then
	echo "mb: error: mbackup config file $configfile not found."
	exit 1
fi

. $configfile

echo "backup files to rsync.net server"

rsync="/usr/bin/rsync"

OPTIONS_BASE="-h --delete-during -a -r --log-file=$rsync_net_log"
# use sylecn's ssh config and private key
OPTIONS_SSH="-e 'ssh -F /home/sylecn/.ssh/config -i /home/sylecn/.ssh/id_rsa'"
# don't show progress for each file when using "mb-online init"
INITOPTIONS="$OPTIONS_SSH $OPTIONS_BASE --exclude-from=$rsync_exclude"
# show progress for each file when using "mb-online"
OPTIONS="--itemize-changes $INITOPTIONS"

TAR=rsync:backup

if [ "$1" == "init" ]
then
	# when doing init tranfer
	# show error if the target dir exists.
	ssh $rsync ls backup/ > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		echo "mb-online: error: old backup detected. "
		echo "please rename rsync:backup/, or old files may get deleted!"
		exit 1
	fi
	# without eval rsync gives parse syntax error
	echo eval sudo $rsync -n --list-only $INITOPTIONS $targetdir $TAR |grep "texts/ac"
else
        # show what's being updated
	echo eval sudo $rsync $OPTIONS $targetdir $TAR
fi

#now backup things in user.private
#source the pri backup script, so env var will be passed to it.
. /home/sylecn/bin/mb-rsync-pri

#give a warning if exclude list is more than 3-day-old
/home/sylecn/bin/cbl $rsync_exclude
