#!/bin/bash
#
# This script backup files from /backup/ to rsync.net server.
# exclude files on private list: user.private
#

configfile="$HOME/.mbackup/config"

if ! [ -e $configfile ]; then
	echo "mb: error: mbackup config file $configfile not found."
	exit 1
fi

. $configfile

echo "backup files to rsync.net server"

rsync="/usr/bin/rsync"

# use sylecn's ssh config and private key
# don't show progress for each file when using "mb-online init"
# use two exclude file
INITOPTIONS="-e 'ssh -F /home/sylecn/.ssh/config -i /home/sylecn/.ssh/id_rsa' -h --delete-during -a -r --log-file=$rsync_net_log --exclude-from=$rsync_exclude"
OPTIONS="--itemize-changes $INITOPTIONS"

TAR=rsync:backup/

if [ "$1" == "init" ]
then
	# when doing init tranfer
	# show error if the target dir exists.
	ssh $rsync ls backup/ > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		echo "mb-online: error: old backup detected. "
		echo "please rename rsync:backup/, or old files may get deleted!"
		exit 1
	fi
	# without eval rsync gives parse syntax error
	eval sudo $rsync -n --list-only $INITOPTIONS $targetdir $TAR |grep "texts/ac"
else
        # show what's being updated
	eval sudo $rsync $OPTIONS $targetdir $TAR
fi

#now backup things in user.private

#use a encrypted virtual disk, rsync to it, then upload that big vdisk file.
#non-free truecrypt
#free http://en.wikipedia.org/wiki/Dm-crypt
private_files="$rsync_exclude"
private_target="$HOME/bak/private.gpg"


#give a warning if exclude list more than 3-day-old
/home/sylecn/bin/cbl $rsync_exclude
