#!/bin/bash
#
# This script backup files from /backup/ to rsync.net server.
# exclude files on private list: user.private
#

PATH=/home/sylecn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

configfile="/home/sylecn/.mbackup/config"

if ! [ -e $configfile ]; then
	echo "mb: error: mbackup config file $configfile not found." > /dev/stderr
	exit 1
fi

. $configfile

rsync="/usr/bin/rsync"

OPTIONS_BASE="-h --delete-during -a -r --log-file=$rsync_net_log --exclude-from=$rsync_exclude"

#
#backup things in user.private
#

#source the pri backup script, so env var will be passed to it.
echo "Updating private files to rsync.net"
. /home/sylecn/bin/mb-rsync-pri
echo "done."

#
#backup things not in user.private
#

TAR=rsync:

if [ "$1" == "init" ]
then
	current_time=`date`
	echo "init started at $current_time"

	# when doing init tranfer
	# show error if the target dir exists.
	ssh $rsync ls backup/ > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		echo "mb-online: error: old backup detected. "
		echo "please rename rsync:backup/, or old files may get deleted!"
		exit 1
	fi
	# without eval rsync gives parse syntax error
	# use -n --list-only -v to do test run,
	# then check /var/log/rsync.net.log because I use -q in init backup.
	# eval sudo $rsync -n --list-only -v $INITOPTIONS $targetdir $TAR
	eval sudo $rsync -q $OPTIONS_BASE $targetdir $TAR

	current_time=`date`
	echo "init ended at $current_time"
else
	echo "Updating public files to rsync.net"
        # show what's being updated
	eval sudo $rsync --progress $OPTIONS_BASE $targetdir $TAR
	echo "done."
fi

#give a warning if exclude list is more than 3-day-old
/home/sylecn/bin/cbl $rsync_exclude
