#!/bin/bash 

#make a tar archive for files in user.publicconfig
#Usage: tarconf [OUTPUT_FILE]
#Sample Usage:
#    tarconf                       backup to default file ~/Dropbox/conf.tar.gz
#    tarconf ~/d/conf.tar.gz       backup to given file

filelist_tarconf="$HOME/.mbackup/backuplists/user.tarconf"
excludelist_tarconf="$HOME/.mbackup/backuplists/tarconf.excl"
excludelist="$HOME/.mbackup/backuplists/auto.exclude"
excludelist_noslash="$HOME/.mbackup/backuplists/auto.tarconf.exclude.noslash"

#default tarfile
tarfile="$HOME/d/conf.tar"

# build $excludelist_noslash
cat $excludelist $excludelist_tarconf | remove-comments "shell" | remove-leading-slash > $excludelist_noslash

if [ -n "$1" ]; then
	tarfile="$1"
fi

cat $filelist_tarconf | remove-nonexists-files | remove-leading-slash | tar cpz -f "$tarfile" \
	-C / \
	-T - \
	--exclude-vcs \
	-X $excludelist_noslash \
	--dereference --hard-dereference --check-links
